# -*- coding: utf-8 -*-
"""love calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lKPYUBIpFlPTNYGgNj_CtzuXt0G8OTkR
"""

print("welcome to love calculator")
name1 = input("name1:\n")
name2 = input("name2:\n")
combined_name = name1+name2
lower_name = combined_name.lower()
t = lower_name.count("t")
r = lower_name.count("r")
u = lower_name.count("u")
e = lower_name.count("e")
total_true = t+r+u+e

l = lower_name.count("l")
o = lower_name.count("o")
v = lower_name.count("v")
e = lower_name.count("e")
total_love = l+o+v+e

total = int(str(total_true) + str(total_love))
if total >40 and total <50:
  print(f"your love score is {total_love} everything is going to be ok")
elif total >50 and total <70:
  print(f" your love score is {total_love} well done couples")
elif total >70 and total <90:
  print(f" your love score is {total_love} lovable couples")
elif total >90:
  print(f" your love score is {total_love} perfect couples")
else:
  print(f" your love score is {total_love} all problems will get solve and going to be a perfect couple")