# -*- coding: utf-8 -*-
"""password generator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17O6tJGV76YXMfK9JEKDWMYFYQGHnVlmO
"""

print("welcome to password generator")
letters = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
numbers = ['1','0','2','3','4','5','6','7','8','9']
symbols = ['!','@','#','$','%','^','&','*','()','+']

nr_letters = int(input("how many letters would u like in ur password:\n"))
nr_symbols = int(input("how many symbols would you like?\n"))
nr_numbers =int(input("how many numbers would u like?\n"))
import random
password =[]
for char in range(1,nr_letters+1):
   random_letter = random.choice(letters)
   password += random_letter

for char in range(1,nr_symbols+1):
  password += random.choice(symbols)

for char in range(1,nr_numbers +1):
  password += random.choice(numbers)

print(password)
random.shuffle(password)
new_password = "".join(password)
print(new_password)

