# -*- coding: utf-8 -*-
"""Rock,Paper,Scissor Game(1)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19varYrJ-sJzYzDovAmAZvlZ7flR_3kIA
"""

Rock = ("""
    _______
---'   ____)
      (_____)
      (_____)
      (____)
---.__(___)
""")

Paper =("""
     _______
---'    ____)____
           ______)
          _______)
         _______)
---.__________)
""")

Scissors =("""
    _______
---'   ____)____
          ______)
       __________)
      (____)
---.__(___)
""")
import random
game_images = [Rock,Paper,Scissors]
user_choice=int(input("choose one number between 0 to 1 where '0 for rock','1 for paper','2 for scissor'."))
print(f"user choice :{user_choice}")
print(game_images[user_choice])

computer_choice = random.randint(0,2)
print(f"computer choose :{computer_choice}")
print(game_images[computer_choice])

if user_choice >=3 or user_choice <0:
  print("itz an invalid number,you loose")
elif user_choice == computer_choice:
  print("itz draw")
elif user_choice ==0 and  computer_choice==2:
  print("you win!!!")
elif user_choice ==2 and  computer_choice==0:
  print("you loose!!!")
elif user_choice > computer_choice:
  print("you loose")
elif user_choice < computer_choice:
  print("you win")

