# -*- coding: utf-8 -*-
"""Roller Coaster

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jfFlIoDw8zPS98s9FqHKrUNE6GzTXKzE
"""

print("welcome to roller coaster ride!!!!")
height = int(input("what is ur height?\n"))
if height > 120:
  bill =0
  print("you are allowed for roller coaster ride")
  age =int(input("what is your age ?\n"))
  if age < 12:
    bill =5
    print("you have to pay $5")
  elif age == 12:
    bill =7
    print("you have to pay $7")
  else:
    bill =9
    print("you have to pay $9 ")
  wants_photo = input("if you want photo type 'y' for yes and 'n' for no.\n").lower()
  if wants_photo == 'y':
    bill +=3
    print("your bill is" ,bill)
  else:
    print("okie enjoy ur ride")
else:
  print("sry!!! you have to grow taller for your roller coaster ride")

