# -*- coding: utf-8 -*-
"""tip calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bEThiSn6GRMSLcausFZIPpVVsg21L__P
"""

print("welcome to tip calculator")
total_bill = int(input("what was the total bill?:\n"))
percent_tip = int(input("what is the percent 10,12 or 15?:\n"))
tips  = percent_tip /100
total_tip_amount = tips * total_bill
split_bill = int(input("how many people to split the bill?:\n"))
split = (total_bill + total_tip_amount)/split_bill
print("here the bill is :",split)