# -*- coding: utf-8 -*-
"""treasure map

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10nKAmG5vi2IMzept_iXxl4aP9BCgKWur
"""

logo =('''*******************************************************************************
          |                   |                  |                     |
 _________|________________.=""_;=.______________|_____________________|_______
|                   |  ,-"_,=""     `"=.|                  |
|___________________|__"=._o`"-._        `"=.______________|___________________
          |                `"=._o`"=._      _`"=._                     |
 _________|_____________________:=._o "=._."_.-="'"=.__________________|_______
|                   |    __.--" , ; `"=._o." ,-"""-._ ".   |
|___________________|_._"  ,. .` ` `` ,  `"-._"-._   ". '__|___________________
          |           |o`"=._` , "` `; .". ,  "-._"-._; ;              |
 _________|___________| ;`-.o`"=._; ." ` '`."\` . "-._ /_______________|_______
|                   | |o;    `"-.o`"=._``  '` " ,__.--o;   |
|___________________|_| ;     (#) `-.o `"=.`_.--"_o.-; ;___|___________________
____/______/______/___|o;._    "      `".o|o_.--"    ;o;____/______/______/____
/______/______/______/_"=._o--._        ; | ;        ; ;/______/______/______/_
____/______/______/______/__"=._o--._   ;o|o;     _._;o;____/______/______/____
/______/______/______/______/____"=._o._; | ;_.--"o.--"_/______/______/______/_
____/______/______/______/______/_____"=.o|o_.--""___/______/______/______/____
/______/______/______/______/______/______/______/______/______/______/[TomekK]
*******************************************************************************

''')
print(logo)
print("welcome to treasure island .your mission is to find treasure")
choice1 = input("choose 'left' or ''right' to reach the treasure:\n").lower()

if choice1 =="left":
  choice2= input("you have choosen the crct path now tell me swim or wait:\n").lower()
  if choice2 =="wait":
    choice3 =input("choose the colour to open the door to rach the treasure:\n").lower()
    if choice3  == "red":
       print("you lose ,you entered in a room full of fire")
    elif choice3 == "blue":
      print("you entered in room full of beast,you lost")
    elif choice3 =="yellow":
      print("you found the treasure you win!!!!!")
    else:
      print("you lose")
  else:
    print("you lose")
else:
  print("sry !!!! you have choosen the wrong route you lose")

